language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t rohithaus/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true rohithaus/docker-react npm run test 

deploy:
  provider: elasticbeanstalk 
  region: "ap-southeast-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-873431790121"
  bucket_path: "docker-react"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
  
  




