FROM node:16-alpine
WORKDIR '/app'
# copy package.json to /app
COPY package.json .
RUN npm install
# after installing the dependencies, copy over everyting else from the project
# directory
COPY . . 
CMD ["npm", "run", "start"]
